import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavigationProgress } from "@/components/navigation-progress";
import { PageLoader } from "@/components/page-loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const magnetik = localFont({
  src: [
    {
      path: "../public/fonts/magnetik-font/Magnetik-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/magnetik-font/Magnetik-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/magnetik-font/Magnetik-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-magnetik",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//DarkMode ShadCN Provider
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${magnetik.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PageLoader />
          <NavigationProgress />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
